### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by yeabow** [kubehan/analyze-logs#1]
<img width="875" alt="image" src="https://github.com/user-attachments/assets/44cddda1-a1ea-411e-a201-79c125e3711b">

<img width="903" alt="image" src="https://github.com/user-attachments/assets/85f29313-33d7-4f36-9924-ff95d8028f77">

**Comment by kubehan** [comment]
多谢提醒，已修正！

> <img alt="image" width="875" src="https://private-user-images.githubusercontent.com/2017715/353806406-44cddda1-a1ea-411e-a201-79c125e3711b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTM5NDUsIm5iZiI6MTcyMjY1MzY0NSwicGF0aCI6Ii8yMDE3NzE1LzM1MzgwNjQwNi00NGNkZGRhMS1hMWVhLTQxMWUtYTIwMS03OWMxMjVlMzcxMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMDI1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE3MDRlZGQwN2RiODk2YmY1M2FmNDZlMzczOTM0MWIyZTA1YjcxMTI0ZWU3NDM2NTc2NTQyYTM1NTJkNGFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LKzOCfmgw2Q28NIlTS8Zeyf51I5p8ze619aNPntfC5k"> <img alt="image" width="903" src="https://private-user-images.githubusercontent.com/2017715/353806719-85f29313-33d7-4f36-9924-ff95d8028f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTM5NDUsIm5iZiI6MTcyMjY1MzY0NSwicGF0aCI6Ii8yMDE3NzE1LzM1MzgwNjcxOS04NWYyOTMxMy0zM2Q3LTRmMzYtOTkyNC1mZjk1ZDgwMjhmNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMDI1NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNmMzE0YjNhOGIwODg2YzQ2NmVhYWU1NjhmMTE0M2FmN2E5OWYxNGE3MzMxYTY4MDYyNDViN2Q0OWMyZTVhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t2xhEKWrsWF-QHewgXqFpG0HafExJAYe5xwNxVKxh_k">
